### ISSUE TITLE
Trying to figure out what one of the games in one of your screenshots is!

### ISSUE THREAD

**Issue by HomeStarRunnerTron** [Fr75s/library#10]
Hi-hi! So sorry to bother you with a non-issue Issue, I just couldn't find any other way to contact you. A few months back, before your updates, I noticed a game in your theme screenshot that I couldn't figure out.

![apfu](https://github.com/Fr75s/library/assets/67088659/03045060-1b79-4979-bd83-4d42f969b89f)

Any chance you could tell me what this is? :  ) Your taste in games is absolutely impeccable. I trust anybody who had Henry Hatsworth in their collection-- [not to mention a Virtual Boy section](https://www.skyetheguy.com/futureboy.png).

Crazy-beautiful theme, man; thank you so much for your inspiring work!

**Comment by Fr75s** [comment]
Hello there,
This is actually a game that I had created. [The game is called Tapfun, and it consists of a collection of 4 minigames.](https://tic80.com/play?cart=1622)

I set up Pegasus to be able to play some TIC-80 games, but since this was before PNG cartridges were added to TIC-80, I created my own box art, so any searching you might have done probably wouldn't have led to much.

Anyways, in case you have any other questions, I am available on Discord (`@fr75s`), or Matrix if that's your thing (`@fr75s:matrix.org`). Thanks for using my theme!

**Comment by HomeStarRunnerTron** [comment]
No stinkin' way, you make games?! Absolutely incredible-- and yes, I tried using Google Reverse Image Search & TinEye to no avail. Do you have a full list of projects you've worked on somewhere? I gotta keep tabs on a creative such as yourself!

<img width="1140" alt="apfuA" src="https://github.com/Fr75s/library/assets/67088659/6cdcd46a-de22-4891-a187-d4fb08a315d6">

That's gotta be the most breakneck Breakout I've ever played-- hilarious distance between the blocks and the bar, hahaha, it definitely adds to the experience. I keep trying to wiggle the bar like crazy to get at the middle, but the moment it actually bounces back, I get too freaked out to catch it.

<img width="1140" alt="apfuB" src="https://github.com/Fr75s/library/assets/67088659/7e2d7195-7cfd-43f1-ab56-a97bc0b632f1">

This one makes me think of something from Big Brain Academy, with the overlapping letter tiles! That's massively hard, but it would be fun to suss out which tile is which pixel-by-pixel. Just need a little more time to do that correctly.

<img width="1140" alt="apfuC" src="https://github.com/Fr75s/library/assets/67088659/a4c528b0-f7b4-4b34-980f-ec9c2d6afeab">

(Also, you probably know this, but there's actually no way to tap out of the Missile Command-- you can just shoot at the buttons up there, hahaha. Cast Missile Command at the darkness!)

Keep up the Awesome work, thank you so much for responding! You've got a great sense of design.
