### ISSUE TITLE
3:4 cover art option

### ISSUE THREAD

**Issue by ZeptoBST** [Fr75s/library#15]
Alot of cover arts are in 3:4, rather than 2:3. As a result, part of the cover arts are cropped.

A toggle would be nice.

**Comment by Fr75s** [comment]
Do you want portrait 3:4 covers or landscape 4:3 covers?
![34_43](https://github.com/Fr75s/library/assets/98292839/6a11f99c-9d0d-4c6d-9e52-fb79f40a9260)

**Comment by ZeptoBST** [comment]
Portrait specifically.

**Comment by ZeptoBST** [comment]
Example: 
![A Hat in Time](https://github.com/Fr75s/library/assets/57198468/d8b131db-366e-4ee4-9018-f2cd5e862f18)


The resolution is 600x800.

**Comment by Fr75s** [comment]
I've added the "Change Aspect Ratios" option in the settings in the latest commit (011c33e), which will change the aspect ratios from 2:3 to 3:4. This is far from a perfect solution, as the boxes are off center now and if you have any covers in an aspect ratio other than 3:4, then they won't be shown in full. I hope that even if it isn't perfect, it is a good enough solution for now (and I could probably fix the boxes being off center, but probably later.)
