### ISSUE TITLE
Aspect ratios don't match steam's

### ISSUE THREAD

**Issue by Hollyrious** [Fr75s/library#2]
Both the wide and portrait artwork boxes do not match either of Steam's aspect ratios for those slots, namely 92:43 for horizontal, and 2:3 for vertical.

**Comment by Fr75s** [comment]
This issue should be fixed now, box aspect ratios should match those for Steam. I did this by making sure the aspect ratio of games remains the same no matter what the window aspect ratio is. This has the consequence of breaking some things when the screen is narrower than 16:10, but as long as you're using a 16:10 screen or wider, you should be okay.
